include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.config.dart
    - test/**/*.config.dart
    - lib/**/*.i18n.dart

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: false
